=== NCEAS/vegbank/web/forms/businessrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="busRule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="notes"/>
        <xs:element ref="sqlSrc"/>
        <xs:element ref="detailFields"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="businessRules">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="busRule" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="detailFields">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="field" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="fieldType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9_]+"/>
    </xs:restriction>
  </xs:simpleType>
 
 
    <xs:element name="field">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="fieldType">
          <xs:attribute name="get" type="xs:boolean"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="notEmpty">
    <xs:restriction base="xs:string">
      <xs:pattern value=".+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="name" type="notEmpty"/>
  <xs:element name="notes" type="notEmpty"/>
  <xs:element name="sqlSrc" type="sqlSrcType"/>
  <xs:simpleType name="sqlSrcType">
    <xs:restriction base="xs:string">
      <xs:pattern value="br_[a-z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== NCEAS/vegbank/web/forms/businessrules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet type="text/xsl" href="businessrules.xsl"?> -->
<businessRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="businessrules.xsd">
  <busRule>
    <name>Confidentiality Reason Required?</name>
    <notes>plot.confidentialityReason needs value if plot is not public</notes>
    <sqlSrc>br_confidentialityreason</sqlSrc>
    <detailFields>
      <field>plot_id</field>
      <field>authorplotcode</field>
      <field>accessioncode</field>
      <field>confidentialitystatus</field>
    </detailFields>
  </busRule>
  <busRule>
    <name>Area pseudo-required</name>
    <notes>We require an area for each plot, unless the plot is stated to be 'Plotless' in the plot.shape field.  Since there are many offenders, detail report is grouped by project.</notes>
    <sqlSrc>br_plotswithoutarea</sqlSrc>
    <detailFields>
      <field>project_id</field>
      <field>projectname</field>
      <field>plotcount</field>
    </detailFields>
  </busRule>
</businessRules>
