=== NCEAS/vegbank/veg_taxa/xmlfiles/taxa.dtd
<!ENTITY % Boolean "(true | false) 'false'">

<!-- JHH 7_2000: first stab at defining a vegetation description model for the plant taxa database

	Purpose:  	this dtd is used for the taxa xml

	Copyright:	2000 Regents of the University of California and the 
			National Center for Ecological Analysis and Synthesis

	Authors:	John Harris

-->

<!-- The root element -->


<!ELEMENT plantTaxa (name,circumscription,party,status,correlation)>

<!ELEMENT name (symbol,taxon,commonName,family,entryDate,nameReference+)>
	<!ELEMENT symbol (#PCDATA)>
	<!ELEMENT taxon (#PCDATA)>
	<!ELEMENT commonName (#PCDATA)>
	<!ELEMENT family (#PCDATA)>
	<!ELEMENT entryDate (#PCDATA)>
	<!ELEMENT nameReference (author,dateEntered,citation,label)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT dateEntered (#PCDATA)>
		<!ELEMENT citation (#PCDATA)>
		<!ELEMENT label (#PCDATA)>
		
<!ELEMENT circumscription (type,circumReference)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT circumReference (author,dateEntered,citation,label)>	

<!ELEMENT party (orgName)>
	<!ELEMENT orgName (#PCDATA)>
	
<!ELEMENT status (currentStatus,statusParty,startDate,stopDate+)>
	<!ELEMENT currentStatus (#PCDATA)>
	<!ELEMENT statusParty (#PCDATA)>
	<!ELEMENT startDate (#PCDATA)>
	<!ELEMENT stopDate (#PCDATA)>	
	
<!ELEMENT correlation (correlationParty, correlationReference, congruence)>
	<!ELEMENT correlationParty (#PCDATA)>
	
	<!ELEMENT correlationReference (correlationAuthor, correlationDateEntered, correlationCitation,label)>
		<!ELEMENT correlationAuthor (#PCDATA)>
		<!ELEMENT correlationDateEntered (#PCDATA)>
		<!ELEMENT correlationCitation (#PCDATA)>
	
	
	<!ELEMENT congruence (#PCDATA)>	
<!-- EOF -->

=== NCEAS/vegbank/veg_taxa/xmlfiles/plantsExample.xml
<?xml version="1.0"?>
<!DOCTYPE plantTaxa SYSTEM "file:C:\plot_database\taxa.dtd">
<plantTaxa>

<!--
from plants 1996
ABBAL|Abies balsamea (L.) P. Mill. ssp. lasiocarpa (Hook.) Boivin|=Abies lasiocarpa var. lasiocarpa|Pinaceae
-->
	
	<name>
		<symbol>ABBAL</symbol>
		<taxon>Abies balsamea (L.) P. Mill. ssp. lasiocarpa (Hook.) Boivin</taxon> 
		<commonName>Abies lasiocarpa var. lasiocarpa</commonName>
		<family> Pinaceae </family>
		<entryDate>2000</entryDate>
		<nameReference>
			<author>Bovin</author>
			<dateEntered>2000</dateEntered>
			<citation>unknown, from plants 1996</citation>
			<label>Abies balsamea (L.) P. Mill. ssp. lasiocarpa (Hook.) Boivin</label> <!--enter species name form plants-->  
		</nameReference>
	</name>
	
	
	<circumscription>
		<type>No</type> <!--always No in the plants-->
		<circumReference>
			<author>Plants1996</author>  <!--plants year-->
			<dateEntered>2000</dateEntered>
			<citation>Plants 1996: plants.usda.gov</citation>  <!--plants year-->
			<label>Abies balsamea (L.) P. Mill. ssp. lasiocarpa (Hook.) Boivin</label>
		</circumReference>
	</circumscription>
	
	<party>
		<orgName>USDA</orgName>  <!--USDA-->
	</party>
	
	<status>
		<currentStatus>NS</currentStatus> <!--because there is an equal sign it is ns else std-->
		<statusParty>USDA</statusParty>  <!--USDA-->
		<startDate>1996</startDate> <!--1996-->
		<stopDate>null</stopDate> <!--no stop date for 96-->
	</status>
	
	
	<correlation>
		<correlationParty>USDA</correlationParty>
			<!--if equal sign (nonstandard) then this party is the USDA-->
			
		<correlationReference>
				<correlationAuthor>Plants1996</correlationAuthor>
				<correlationDateEntered>2000</correlationDateEntered>
				<correlationCitation>Plants 1996: plants.usda.gov</correlationCitation>
		 		<label>Abies lasiocarpa var. lasiocarpa</label> 
		</correlationReference>
		
		<congruence>equal</congruence> 
	</correlation>
	
	
</plantTaxa>
