=== NCEAS/vegbank/veg_plot/plot_database/geographic_metadata.dtd
<!ENTITY % Boolean "(true | false) 'false'">

<!-- JHH 7_2000: first stab at defining an object geographic metedata model for 
		the vegetation plot database

	Purpose:  	this dtd represents components of the FGDC Metadata DTD 3.0.1 19990611, 
			corresponding to the June, 1998 version of the standard, FGDC-STD-001-1998
			'Content Standard for Digital Geospatial Metadata' loacted in the 
			csdgm-fgdc-std-001-1998.pdf

	Copyright:	2000 Regents of the University of California and the 
			National Center for Ecological Analysis and Synthesis

	Authors:	John Harris

-->

<!-- The root element -->
<!ENTITY % geographicCondition "(spdom,altsys,slope,browse+)">
<!ELEMENT geographicCondition    (spdom,altsys,slope,browse+)>

<!--Spatial Domain-->
<!ELEMENT spdom    (bounding, dsgpoly*)>  

<!--Bounding Coordinates with the bounding altitude added to be consistent with the nbii-fgdc-std-001.1-1999.dtd-->
<!ELEMENT bounding (westbc, eastbc, northbc, southbc, boundalt)>  
<!ELEMENT westbc   (#PCDATA)>  		<!-- west bounding coordinate -->
<!ELEMENT eastbc   (#PCDATA)>		<!-- east bounding coordinate -->
<!ELEMENT northbc   (#PCDATA)>		<!-- north bounding coordinate -->
<!ELEMENT southbc   (#PCDATA)>		<!-- south bounding coordinate -->
<!ELEMENT boundalt (altmin, altmax)>	<!--left out the altunits b/c it shows up in 'altsys'--> 
<!ELEMENT altmin   (#PCDATA)>		<!--Altitude Minimum-->
<!ELEMENT altmax   (#PCDATA)>		<!--Altitude Maximum-->


<!ELEMENT dsgpoly  (dsgpolyo, dsgpolyx*)>  <!--Data Set G-Polygon coordinates defining the outline of an area covered by a data set--> 

<!ELEMENT dsgpolyo ((grngpoin,grngpoin,grngpoin,grngpoin+) | gring)> <!--Data Set G-Polygon Outer G-Ring 
												the closed nonintersecting boundry of 
												an interior area-->

<!ELEMENT dsgpolyx ((grngpoin,grngpoin,grngpoin,grngpoin+) | gring)> <!--Data Set G-Polygon Exclusion G-Ring 
												a "hole" in the interior area-->

<!--Altitude measurements of Bounding Coordinates-->

<!ELEMENT grngpoin (gringlat,gringlon)>  <!--G-Ring Point a single geographic loaction-->
<!ELEMENT gringlat (#PCDATA)>			<!-- the latitude of a Point of a G-Ring-->
<!ELEMENT gringlon (#PCDATA)>			<!-- the longitude of a Point of a G-Ring-->
<!ELEMENT gring  (#PCDATA)>  			<!--pair of floating point latitude and logitude points-->

<!--Altitude System description-->
<!ELEMENT altsys (altdatum, altres+, altunits, altenc)>
<!ELEMENT altdatum (#PCDATA)>  <!--Altitude Datum -->
<!ELEMENT altres (#PCDATA)>  <!--Altitude Resolution-->
<!ELEMENT altunits (#PCDATA)>  <!--Altitude Distance Units-->
<!ELEMENT altenc (#PCDATA)>  <!--Altitude encoding scheme-->

<!--Description of Dip from FGDC-STD-006 Soil Geographic Data Standard very general-->
<!ELEMENT slope (slope_aspect, slope_gradient)>
<!ELEMENT slope_aspect (#PCDATA)>  <!--Azimuth-->
<!ELEMENT slope_gradient (#PCDATA)>  <!--Dip Angle-->


<!-- Graphical Information-->
<!ELEMENT browse (browsen, browsed, browset)>
<!ELEMENT browsen (#PCDATA)>  <!--Graphical file name which is an illustration of the dataset-->
<!ELEMENT browsed (#PCDATA)>  <!--Graphical file description-->
<!ELEMENT browset (#PCDATA)>  <!--Graphical file extension-->

<!--Maybe put security attributes here-->


<!-- EOF -->

=== NCEAS/vegbank/veg_plot/plot_database/geographic_metadata_example.xml
<?xml version="1.0" encoding="Cp1252"?>
<!DOCTYPE geographicCondition SYSTEM "file:C:\plot_database\geographic_metadata.dtd">

<!-- Root Element -->

<geographicCondition>
<spdom>
	<bounding>
		<westbc>westernmost bounding coordiante</westbc>
		<eastbc>easternmost bounding coordiante</eastbc>
		<northbc>northernmost bounding coordiante</northbc>
		<southbc>soutrhernmost bounding coordiante</southbc>
		<boundalt>
			<altmin>altitudeMinimum</altmin>
			<altmax>altitudeMaximum</altmax>
		</boundalt>

	</bounding>

	<dsgpoly>
		<dsgpolyo>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>




		</dsgpolyo>
		
		<dsgpolyx>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>	
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>
			<grngpoin>
				<gringlat>latitude</gringlat>
				<gringlon>longitude</gringlon>
			</grngpoin>


		</dsgpolyx>
		
		
	</dsgpoly>

</spdom>

<!--Altitude Description  FGDC-STD-001-1998.pdf 4.2.1.1-->
<altsys>
	<altdatum>altitudeDatum</altdatum>
	<altres>altitudeResolution</altres>
	<altunits>altitudeUnits</altunits>
	<altenc>altitudeEncoding</altenc>
</altsys>


<!--Description of Dip from FGDC-STD-006 Soil Geographic Data Standard very general-->
<slope>
	<slope_aspect>slopeAzimuth</slope_aspect>
	<slope_gradient>slopeDip</slope_gradient>
</slope>


<!--Graphical data information-->
<browse>
	<browsen>graphic.Name</browsen>
	<browsed>graphic.Description</browsed>
	<browset>graphic.Type</browset>
</browse>
</geographicCondition>
