=== NCEAS/vegbank/veg_plot/plot_database/veg_plot_dtd.dtd
<!ENTITY % Boolean "(true | false) 'false'">

<!-- JHH 7_2000: first stab at defining an object model for the plots database -->


<!ELEMENT veg_plot (plot_id,PI*,contact*,class_association,class_alliance,classification_quality,author_plot_number,previous_plot_record,
previous_plot_number, author,date,ownership,media,effort_level,disturbance_history)>
<!ATTLIST veg_plot preferred (true|false) 'true'>

<!ELEMENT plot_id (#PCDATA)>

<!-- Pricipal Investigator as well as the metadata accosiated with that person -->
<!ELEMENT PI (pid,pid_metadata+)>
<!ELEMENT pid (#PCDATA)>
<!ELEMENT pid_metadata (institution,address,phone,email)>
<!ATTLIST pid_metadata preferred (true|false) 'true'>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!--Main Contact Person and the associated metadata withe that person-->
<!ELEMENT contact (contact_pid,contact_pid_metadata)>
<!ELEMENT contact_pid (#PCDATA)>
<!ELEMENT contact_pid_metadata (contact_institution,contact_address,contact_phone,contact_email)>
<!ATTLIST contact_pid_metadata preferred (true|false) 'true'>
<!ELEMENT contact_institution (#PCDATA)>
<!ELEMENT contact_address (#PCDATA)>
<!ELEMENT contact_phone (#PCDATA)>
<!ELEMENT contact_email (#PCDATA)>


<!ELEMENT class_association (#PCDATA)>
<!ELEMENT class_alliance (#PCDATA)>
<!ELEMENT clasification_quality (#PCDATA)>
<!ELEMENT author_plot_number (#PCDATA)>
<!ELEMENT previous_plot_record (#PCDATA)>
<!ELEMENT previous_plot_number (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT ownership (#PCDATA)>
<!ELEMENT media (#PCDATA)>
<!ELEMENT effort_level (#PCDATA)>
<!ELEMENT disturbance_history (#PCDATA)>

=== NCEAS/vegbank/veg_plot/plot_database/veg_plot_xml.xml
<?xml version="1.0" encoding="Cp1252"?>
<!DOCTYPE veg_plot SYSTEM "file:C:\plot_database\veg_plot_dtd.dtd">
<veg_plot preferred="true">
<plot_id>4444444</plot_id>
	<PI>
		<pid>this is the id number of the pi</pid>
		<pid_metadata>
			<institution>null</institution>
			<address>null</address>
			<phone>null</phone>
			<email>null</email>
		</pid_metadata>
	</PI>
	<contact>
	<contact_pid>this is the id number of the contact person</contact_pid>
		<contact_pid_metadata>
			<contact_institution>null</contact_institution>
			<contact_address>null</contact_address>
			<contact_phone>null</contact_phone>
			<contact_email>null</contact_email>
		</contact_pid_metadata>

	</contact>
	<class_association>pomaguliad bush</class_association>
	<class_alliance>goatsum</class_alliance>
	<clasification_quality>high</clasification_quality>
	<author_plot_number>personal reference</author_plot_number>
	<previous_plot_number>old name or number</previous_plot_number>
	<previous_plot_record>previous plot number</previous_plot_record>
	<author>worker who described the plot</author>
	<date>date of vegetation plot</date>
	<ownership>who owns the land</ownership>
	<media>any photographs, maps and/or other media</media>
	<effort_level>effort spent bulding the plot</effort_level>
	<disturbance_history>the land disturbance history</disturbance_history>

</veg_plot>
