=== NCEAS/vegbank/veg_plot/plot_database/veg_description.dtd
<!ENTITY % Boolean "(true | false) 'false'">

<!-- JHH 7_2000: first stab at defining a vegetation description model for the veg plots database

	Purpose:  	this dtd is used for the vegetaion description xml

	Copyright:	2000 Regents of the University of California and the 
			National Center for Ecological Analysis and Synthesis

	Authors:	John Harris

-->

<!-- The root element -->

<!ENTITY % vegetation_description "(plot_id, species+)">
<!ELEMENT vegetation_description (plot_id, species+)>


<!ELEMENT plot_id (#PCDATA)>
<!ELEMENT species (orig_species,stratum+)>
<!ELEMENT orig_species (#PCDATA)>
<!ELEMENT stratum (stratum_type, percent_cover, dominance)>
<!ELEMENT stratum_type (#PCDATA)>
<!ELEMENT percent_cover (#PCDATA)>
<!ELEMENT dominance (id, layer_height, physiogn_A, physiogn_B)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT layer_height (#PCDATA)>
<!ELEMENT physiogn_A (#PCDATA)>
<!ELEMENT physiogn_B (#PCDATA)>




<!-- EOF -->

=== NCEAS/vegbank/veg_plot/plot_database/test_desc.xml
<?xml version="1.0"?>
<!DOCTYPE vegetation_description SYSTEM "file:C:\plot_database\veg_description.dtd">
<vegetation_description>
	<plot_id>100</plot_id>

	<species>
		<orig_species>QuakingwoodyBush</orig_species>
		<stratum>
			<stratum_type>herb</stratum_type>
			<percent_cover>20</percent_cover>
				<dominance>
					<id>yes</id>
					<layer_height>200'</layer_height>
					<physiogn_A>Evergreen</physiogn_A>
					<physiogn_B>needle-leaved</physiogn_B>
				</dominance>
		</stratum>
	</species>
<species>
<orig_species>redpine</orig_species>
<stratum>
<stratum_type>tree</stratum_type>
<percent_cover>30</percent_cover>
<dominance>
<id>no</id>
<layer_height/>
<physiogn_A/>
<physiogn_B/>
</dominance>
</stratum>
</species>
</vegetation_description>

=== NCEAS/vegbank/veg_plot/plot_database/servlet_output.file.xml
<?xml version="1.0"?>
<!DOCTYPE vegetation_description SYSTEM "file:C:\plot_database\veg_description.dtd">
<vegetation_description>
<plot_id>mike</plot_id>
<species>
<orig_species>john</orig_species>
<stratum>
<stratum_type>tree</stratum_type>
<percent_cover></percent_cover>
<dominance>
<id></id>
<layer_height></layer_height>
<physiogn_A></physiogn_A>
<physiogn_B></physiogn_B>
</dominance>
</stratum>
</species>
</vegetation_description>
