=== NCEAS/vegbank/veg_plot/xml/vegPlot.dtd
<!ENTITY % Boolean "(true | false) 'false'">

<!-- JHH 2000  DTD which will be parsed into the vegplot database -->

<!ELEMENT vegPlot (project)>




<!ELEMENT project (projectName, projectDescription, plot, projectContributor)>
<!ELEMENT projectName (#PCDATA)>
<!ELEMENT projectDescription (#PCDATA)>

<!ELEMENT projectContributor (role, party)>
	<!ELEMENT role (#PCDATA)>
	<!ELEMENT party (salutation, givenName, surName, organizationName, positionName, hoursOfService, contactInstructions, 
	onlineResource, telephone, email, address)>
		<!ELEMENT salutation (#PCDATA)>
		<!ELEMENT givenName (#PCDATA)>
		<!ELEMENT surName (#PCDATA)>
		<!ELEMENT organizationName (#PCDATA)>
		<!ELEMENT  positionName (#PCDATA)>
		<!ELEMENT hoursOfService (#PCDATA)>
		<!ELEMENT contactInstructions (#PCDATA)>

		<!ELEMENT onlineResource (linkage, protocol, name, applicationProfile, description)>
			<!ELEMENT linkage (#PCDATA)>
			<!ELEMENT protocol (#PCDATA)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT applicationProfile (#PCDATA)>
			<!ELEMENT description (#PCDATA)>
		<!ELEMENT telephone (phoneNumber, phoneType)>
			<!ELEMENT phoneNumber (#PCDATA)>
			<!ELEMENT phoneType (#PCDATA)>
		<!ELEMENT email (emailAddress)>
			<!ELEMENT emailAddress (#PCDATA)>
		<!ELEMENT address (deliveryPoint, city, administrativeArea, postalCode, country, currentFlag)>
			<!ELEMENT deliveryPoint (#PCDATA)>
			<!ELEMENT city (#PCDATA)>
			<!ELEMENT administrativeArea (#PCDATA)>
			<!ELEMENT postalCode (#PCDATA)>
			<!ELEMENT country (#PCDATA)>
			<!ELEMENT currentFlag (#PCDATA)>

<!ELEMENT plot (authorPlotCode, parentPlot, plotType, samplingMethod, coverScale, plotOriginLat,
	 plotOriginLong, plotShape, plotSize, plotSizeAcc, altValue, altPosAcc, slopeAspect, slopeGradient,
	 slopePosition, hydrologicRegime, soilDrainage, surfGeo, plotObservation, namedPlace, stand, 
	graphic, plotContributor)>
 	<!ELEMENT authorPlotCode (#PCDATA)>
	 <!ELEMENT parentPlot (#PCDATA)>
	 <!ELEMENT plotType (#PCDATA)>
	 <!ELEMENT samplingMethod (#PCDATA)>
	 <!ELEMENT coverScale (#PCDATA)>
	 <!ELEMENT plotOriginLat (#PCDATA)>
	 <!ELEMENT plotOriginLong (#PCDATA)>
	 <!ELEMENT plotShape (#PCDATA)>
	 <!ELEMENT plotSize (#PCDATA)>
	 <!ELEMENT plotSizeAcc (#PCDATA)>
	 <!ELEMENT altValue (#PCDATA)>
	 <!ELEMENT altPosAcc (#PCDATA)>
	 <!ELEMENT slopeAspect (#PCDATA)>
	 <!ELEMENT slopeGradient (#PCDATA)>
	 <!ELEMENT slopePosition (#PCDATA)>
	 <!ELEMENT hydrologicRegime (#PCDATA)>
	 <!ELEMENT soilDrainage (#PCDATA)>
	 <!ELEMENT surfGeo (#PCDATA)>

	<!ELEMENT plotObservation (previousPlot, plotStartDate, plotStopDate, 
	dateAccuracy, effortLevel,  strata, taxonObservations, communityType, citation)>
		<!ELEMENT previousPlot (#PCDATA)>
		<!ELEMENT plotStartDate (#PCDATA)>
		<!ELEMENT plotStopDate (#PCDATA)>
		<!ELEMENT dateAccuracy (#PCDATA)>
		<!ELEMENT effortLevel (#PCDATA)>
		<!ELEMENT strata (stratumCover, stratumHeight)>
			<!ELEMENT stratumCover (#PCDATA)>
			<!ELEMENT stratumHeight (#PCDATA)>

		<!ELEMENT taxonObservations (authNameId, originalAuthority, strataComposition, interptretation)>
			<!ELEMENT authNameId (#PCDATA)>
			<!ELEMENT originalAuthority (#PCDATA)>
			<!ELEMENT strataComposition (strataType, percentCover)>
				<!ELEMENT strataType (#PCDATA)>
				<!ELEMENT percentCover (#PCDATA)>	

			<!ELEMENT interpretation (party, taxonName, authority, usageStartDate, usageStopDate, circum_id, role, date, notes)>
				<!ELEMENT party (#PCDATA)>
				<!ELEMENT taxonName (#PCDATA)>
				<!ELEMENT authority (#PCDATA)>
				<!ELEMENT usageStartDate (#PCDATA)>
				<!ELEMENT usageStopDate (#PCDATA)>
				<!ELEMENT circum_id (#PCDATA)> 
				<!ELEMENT role (#PCDATA)> 
				<!ELEMENT date (#PCDATA)> 
				<!ELEMENT notes (#PCDATA)> 
	
		<!ELEMENT communityType (classAssociation, classQuality, startDate, stopDate)>
			<!ELEMENT classAssociation (#PCDATA)>
			<!ELEMENT classQuality (#PCDATA)>
			<!ELEMENT strartDate (#PCDATA)>
			<!ELEMENT stopDate (#PCDATA)>

		<!ELEMENT citation (title, altTitle, pubDate, edition, editionDate, seriesName, 
		issueIdentification, otherCredentials, 
			page, isbn, issn,citationContributor)>
			<!ELEMENT title (#PCDATA)>
			<!ELEMENT altTitle (#PCDATA)>
			<!ELEMENT pubDate (#PCDATA)>
			<!ELEMENT edition (#PCDATA)>
			<!ELEMENT editionDate (#PCDATA)>
			<!ELEMENT seriesName (#PCDATA)>
			<!ELEMENT issueIdentification (#PCDATA)>
			<!ELEMENT otherCredentials (#PCDATA)>
			<!ELEMENT page (#PCDATA)>
			<!ELEMENT isbn (#PCDATA)>
			<!ELEMENT issn (#PCDATA)>

			<!ELEMENT citationContributor (role,party)>


	<!ELEMENT namedPlace (placeName, placeDescription, gazeteerRef)>
		<!ELEMENT placeName (#PCDATA)>
		<!ELEMENT placeDescription (#PCDATA)>
		<!ELEMENT gazeteerRef (#PCDATA)>

	<!ELEMENT stand (standSize, standDescription, standName)>
		<!ELEMENT standSize (#PCDATA)>
		<!ELEMENT standDescription (#PCDATA)>
		<!ELEMENT standName (#PCDATA)>

	<!ELEMENT  graphic (browseName, browseDescription, browseType, browseData)>
		<!ELEMENT browseName (#PCDATA)>
		<!ELEMENT browseDescription (#PCDATA)>
		<!ELEMENT browseType (#PCDATA)>
		<!ELEMENT browseData (#PCDATA)>

	<!ELEMENT  plotContributor (role,party)>

=== NCEAS/vegbank/veg_plot/xml/vegPlotExample.xml
<?xml version="1.0"?>
<!DOCTYPE vegPlot   SYSTEM "vegPlot.dtd">

<vegPlot>	
<project>
	<projectName>Name of the project! </projectName>
	<projectDescription> </projectDescription>	
	<projectContributor>
		<role> </role>
		<party> 
			<salutation> </salutation>
			<givenName>  </givenName>
			<surname> </surname>
			<organizationName> </organizationName>
			<positionName> </positionName>
			<hoursOfService> </hoursOfService>
			<contactInstructions> </contactInstructions>

			<onlineResource>
				<linkage> </linkage>
				<protocol> </protocol>
				<name> </name>
				<applicationProfile> </applicationProfile>
				<description> </description>
			</onlineResource>

			<telephone>
				<phoneNumber></phoneNumber>
				<phoneType> </phoneType>
			</telephone>

			<email>
				<emailAddress> </emailAddress>
			</email>

			<address>
				<deliveryPoint> </deliveryPoint>
				<city> </city>
				<administrativeArea> </administrativeArea>
				<postalCode> </postalCode>
				<country> </country>
				<currentFlag> </currentFlag>
			</address>
		</party>
	</projectContributor>

	<plot>
		<authorPlotCode> </authorPlotCode>
		<parentPlot> </parentPlot>
		<plotType> </plotType>
		<samplingMethod> </samplingMethod>
		<coverScale> </coverScale>
		<plotOriginLat> </plotOriginLat>
		<plotOriginLong> </plotOriginLong>
		<plotShape> </plotShape>
		<plotSize> </plotSize>
		<plotSizeAcc> </plotSizeAcc>
		<altValue> </altValue>
		<altPosAcc> </altPosAcc>
		<slopeAspect> </slopeAspect>
		<slopeGradient> </slopeGradient>
		<slopePosition> </slopePosition>
		<hydrologicRegime> </hydrologicRegime>
		<soilDrainage> </soilDrainage>
		<surfGeo> </surfGeo>

		<plotObservation>
			<previousPlot> </previousPlot>
			<plotStartDate> </plotStartDate>
			<plotStopDate> </plotStopDate>
			<dateAccuracy> </dateAccuracy>
			<effortLevel> </effortLevel>
			
			<strata>
				<stratumCover> </stratumCover>
				<stratumHeight> </stratumHeight>
			</strata>


			<taxonObservations>
				<authNameId> </authNameId>
				<originalAuthority> </originalAuthority>
				<strataComposition>
					<strataType> </strataType>
					<percentCover> </percentCover>
				</strataComposition>
				
				<interptretation>
					<circum_id> </circum_id>
					<role> </role>
					<date> </date>
					<notes> </notes>	
				</interptretation>
			</taxonObservations>
			
			<communityType>
				<classAssociation> </classAssociation>
				<classQuality> </classQuality>
				<startDate> </startDate>
				<stopDate> </stopDate>
			</communityType>


			<citation>
				<title> </title>
				<altTitle> </altTitle>
				<pubDate> </pubDate>
				<edition> </edition>
				<editionDate> </editionDate>
				<seriesName> </seriesName>
				<issueIdentification> </issueIdentification>
				<otherCredentials> </otherCredentials>
				<page> </page>
				<isbn> </isbn>
				<issn> </issn>

				<citationContributor>
					
				</citationContributor>			

			</citation>
		</plotObservation>

 		<namedPlace>
			<placeName> </placeName>
			<placeDescription> </placeDescription>
			<gazeteerRef> </gazeteerRef>
		</namedPlace>

		<stand>
			<standSize> </standSize>
			<standDescription> </standDescription>
			<standName> </standName>	
		</stand>


		<graphic>
			<browseName> </browseName>
			<browseDescription> </browseDescription>
			<browseType> </browseType>
			<browseData> </browseData>
		</graphic>

		<plotContributor> 
			<role> </role>
			<party> </party>
		</plotContributor>


	</plot>


</project>
</vegPlot>
