=== NCEAS/vegbank/docs/tableStructure.dtd
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!ENTITY % Boolean "(true | false) 'false'">
<!ELEMENT dataModel (title, author, institution, contributor, description, date, entity)>
<!ELEMENT entity (entityName*, entitySummary*, entityDescription*, module, attribute*, children*, childrenRef*)>
<!ELEMENT attribute (attName, attNulls, attType, attKey, attReferences, attNotes, attDefinition, defaultValue*, TVCompliant*, TVName*, businessRules*)>
<!ELEMENT businessRules (constraintAttribute | required | (minCharacterLength | maxCharacterLength)* | (minNumericValue, maxNumericValue))>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT contributor (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT entityName (#PCDATA)>
<!ELEMENT entitySummary (#PCDATA)>
<!ELEMENT entityDescription (#PCDATA)>
<!ELEMENT attName (#PCDATA)>
<!ELEMENT attNulls (#PCDATA)>
<!ELEMENT attType (#PCDATA)>
<!ELEMENT attKey (#PCDATA)>
<!ELEMENT attReferences (#PCDATA)>
<!ELEMENT attNotes (#PCDATA)>
<!ELEMENT attDefinition (#PCDATA)>
<!ELEMENT TVCompliant (#PCDATA)>
<!ELEMENT TVName (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT children (#PCDATA)>
<!ELEMENT childrenRef (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT constraintAttribute (#PCDATA)>
<!ELEMENT minCharacterLength (#PCDATA)>
<!ELEMENT maxCharacterLength (#PCDATA)>
<!ELEMENT minNumericValue (#PCDATA)>
<!ELEMENT maxNumericValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!-- -->

=== NCEAS/vegbank/docs/xml/commtaxa/commTaxaCommUsage.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: commUsage</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>7 February 2002</date>
	<entity>
		<entityName>commTaxa.commUsage</entityName>
		<entitySummary>This table links a community name with a concept.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>COMMUSAGE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the communityUsage table.</attDefinition>
		</attribute>
		<attribute>
			<attName>COMMNAME_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>commName.COMMNAME_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This field is the foreign key into the commName table.</attDefinition>
		</attribute>
		<attribute>
			<attName>COMMCONCEPT_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>commConcept.COMMCONCEPT_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This field is the foreign key into the commConcept table.</attDefinition>
		</attribute>
		<attribute>
			<attName>usageStart</attName>
			<attNulls>No</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the date on which the party applied the name to the concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>usageStop</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the date on which the party ceased to apply the name to the concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>commNameStatus</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>This field shows the status of the application of the name to the concept by the party (standard, not standard, undetermined).</attDefinition>
		</attribute>
		<attribute>
			<attName>COMMPARTY_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>commParty.COMMPARTY_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Foreign key that identifies the party that used the class concept with the name.</attDefinition>
		</attribute>
		<attribute>
			<attName>classSystem</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Like FGDC of Forest Cover Class.</attNotes>
			<attDefinition>This is the name of the classification system wherein the name is applied (e.g., Scientific, Spanish common).</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/commTaxaCommReference.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: commCitation</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date/>
	<entity>
		<entityName>comm.commCitation</entityName>
		<entitySummary>This table stores references which are linked to community concepts.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>CITATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in 	the commReference table.</attDefinition>
		</attribute>
		<attribute>
			<attName>citation</attName>
			<attNulls>No</attNulls>
			<attType>TEXT</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Field stores the citation.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/vegplot/vegPlotAddress.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: address</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>31 October 2001</date>
	<entity>
		<entityName>vegPlot.address </entityName>
		<entitySummary>This table contains the postal address, email address and/or organizational affiliation for a parties at the time of a plot event. </entitySummary>
		<entityDescription/>
		<attribute>
			<attName>ADDRESS_ID</attName>
			<attNulls>No </attNulls>
			<attType>INT</attType>
			<attKey>PK </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>Primary key for the address table. </attNotes>
			<attDefinition>Database generated identifier assigned to each unique party address (note that a single party may have multiple addresses but that only one may be 'current').</attDefinition>
		</attribute>
		<attribute>
			<attName>PARTY_ID </attName>
			<attNulls>No </attNulls>
			<attType>INT</attType>
			<attKey>FK </attKey>
			<attReferences>party.PARTY_ID </attReferences>
			<attNotes>Foreign key into the party table. </attNotes>
			<attDefinition>Link to the party to which this address applies</attDefinition>
		</attribute>
		<attribute>
			<attName>ORGANIZATION_ID</attName>
			<attNulls>Yes</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>party.PARTY_ID </attReferences>
			<attNotes>Foreign key into the party table</attNotes>
			<attDefinition>Link to an organization with which a party is affiliated</attDefinition>
		</attribute>
		<attribute>
			<attName>orgPosition</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Position of party within organization.</attDefinition>
		</attribute>
		<attribute>
			<attName>email</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(100)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>email address</attDefinition>
		</attribute>
		<attribute>
			<attName>deliveryPoint </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(200)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Address line for the location
(Street name, box number, suite).</attDefinition>
		</attribute>
		<attribute>
			<attName>city </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>City of the location. </attDefinition>
		</attribute>
		<attribute>
			<attName>administrativeArea </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>State, province of the location. </attDefinition>
		</attribute>
		<attribute>
			<attName>postalCode </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(10)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Zip code or other postal code. </attDefinition>
		</attribute>
		<attribute>
			<attName>country </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Country of the physical address. </attDefinition>
		</attribute>
		<attribute>
			<attName>currentFlag </attName>
			<attNulls>Yes</attNulls>
			<attType>BOOLEAN</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>This flag signifies whether the address is the current address of the party. </attDefinition>
		</attribute>
		<attribute>
			<attName>addressStartDate</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The first database date on which the address/organization information applied (have a discrete date on which address is known to applied -- not necessarily the first date on which the address applied).</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/communityTaxaCommunityUsage.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	
<title>Prototype Veg Plots Database Component Description: communityUsage</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>



<entity>
	<entityName>community.communityUsage</entityName>
	<entitySummary>This table links a community name with a concept.</entitySummary>
	<entityDescription> </entityDescription>
	<attribute> 
		<attName>COMMUNITYUSAGE_ID</attName>
		<attNulls>No</attNulls>	
		<attType>NUMBER</attType>
		<attKey>PK</attKey>
		<attReferences>n/a</attReferences>
		<attNotes>n/a</attNotes>
		<attDefinition>Database assigned value to each unique record in 
		the communityUsage table.</attDefinition>
	</attribute>



	<attribute>
                <attName>COMMUNITYNAME_ID</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>FK</attKey>
                <attReferences>communityName</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This field is the foreign key into the communityName 
		table.</attDefinition>
        </attribute>

	<attribute>
                <attName>COMMUNITYCONCEPT_ID</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>FK</attKey>
		<attReferences>communityConcept</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This field is the foreign key into the communityConcept 
		table.</attDefinition>
        </attribute>

	<attribute>
                <attName>usageStart</attName>
                <attNulls>NO</attNulls>
                <attType>DATE</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This is the date on which a name was first applied 
		to a concept.</attDefinition>
        </attribute>
	
	<attribute>
                <attName>usageStop</attName>
                <attNulls>NO</attNulls>
                <attType>DATE</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This is the date on which a name no longer was being 
		applied to a concept.</attDefinition>
        </attribute>
	
	<attribute> 
		<attName>communityNameStatus</attName>
		<attNulls>No</attNulls>	
		<attType>VARCHAR2</attType>
		<attKey>n/a</attKey>
		<attReferences>n/a</attReferences>
		<attNotes>n/a</attNotes>
		<attDefinition>This field stores an indicator of whether a community 
		name is of standard status or not per the party designated in the 
		next field.</attDefinition>
	</attribute>
	
	<attribute>
                <attName>party</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
		<attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This is the name of the party that uses the class 
		concept with the name.</attDefinition>
        </attribute>

	<attribute>
                <attName>classSystem</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
		<attReferences>n/a</attReferences>
                <attNotes>Like FGDC of Forest Cover Class.</attNotes>
                <attDefinition>This is the name of the system that the class (from 
		the communityConcept) falls into.</attDefinition>
        </attribute>

	
	


	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotOnlineResource.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	

<title> Prototype Veg Plots Database Component Description: onlineResource</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>



<entity>
	<entityName>vegPlot.ONLINERESOURCE </entityName>
	<entitySummary>This table stores information about a party's online resources. </entitySummary>
	<entityDescription> </entityDescription>
	<attribute> 
		<attName>ONLINERESOURCE_ID</attName>
		<attNulls>No </attNulls>	
		<attType>NUMBER </attType>
		<attKey>PK </attKey>
		<attReferences>n/a </attReferences>
		<attNotes>Primary key for onlineResource table. </attNotes>
		<attDefinition>Database assigned value to each unique record in the onlineResource table. </attDefinition>
	</attribute>



	<attribute>
                <attName>PARTY_ID</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>FK </attKey>
                <attReferences>vegPlotParty </attReferences>
                <attNotes>Foreign key into the PARTY table. </attNotes>
                <attDefinition>Database assigned value that is unique to each party
                                  contributing in the collection of plots.
		 </attDefinition>
        </attribute>


	<attribute>
                <attName>linkage</attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
		<attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Location (address) for on-line access using a
                                  Uniform Resource Locator address or similar
                                  addressing scheme such as:
                                  http://www.nceas.ucsb.edu.
		 </attDefinition>
        </attribute>



        <attribute>
                <attName>protocol </attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
                <attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Connection protocol to be used. </attDefinition>
        </attribute>
	
	<attribute>
                <attName>name </attName>
                <attNulls>No </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
		<attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Name of the resource.</attDefinition>
        </attribute>



        <attribute>
                <attName>applicationProfile </attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
                <attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Name of the application profile that can be used with the resource. </attDefinition>
        </attribute>

	<attribute>
                <attName>description </attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a </attKey>
		<attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Description of what the resource is/does. </attDefinition>
        </attribute>





	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/planttaxa/plantTaxaPlantCorrelation.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: plantCorrelation</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date/>
	<entity>
		<entityName>planttaxa.plantCorrelation</entityName>
		<entitySummary>This table correlates multiple plant concepts as they 
change through time.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>PLANTCORRELATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the plantCorrelation table.</attDefinition>
		</attribute>
		<attribute>
			<attName>PLANTSTATUS_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantStatus.PLANTSTATUS_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the foreign key into the plantStatus table "pointing" to a concept no longer viewed as standard by the party.</attDefinition>
		</attribute>
		<attribute>
			<attName>PLANTCONCEPT_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantConcept.PLANTCONCEPT_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the foreign key into the plantConcept table "pointing" to a concept recognized by the party as a "standard" concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>plantConvergence</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>This is the descriptive attribute that is used to relate the congruence between two concepts.</attDefinition>
		</attribute>
		<attribute>
			<attName>correlationStart</attName>
			<attNulls>No</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the start date for recognition by a party of a correlation between two concepts.</attDefinition>
		</attribute>
		<attribute>
			<attName>correlationStop</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the stop date for recognition by a party of a correlation between two concepts.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/planttaxa/plantTaxaPlantConcept.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: plantConcept</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date/>
	<entity>
		<entityName>plantTaxa.plantConcept</entityName>
		<entitySummary>This table store the concepts that are linked to plant names through the plantUsage table.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>PLANTCONCEPT_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the commConcept table.</attDefinition>
		</attribute>
		<attribute>
			<attName>PLANTNAME_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantName.PLANTNAME_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is a foreign key into the plant name list, the entery in which when combined wiht a reference constitutes a concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>PLANTREFERENCE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantReference.PLANTREFERENCE_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is a foreign key to the reference in which the name was used, thereby defining a concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>plantLevel</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The classLevel attribute specifies a level in the taxonomic hierarcy that a class belongs.</attDefinition>
		</attribute>
		<attribute>
			<attName>plantParent</attName>
			<attNulls>Yes</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantConcept.PLANTCONCEPT_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The plantParent is a recursive key to the concept of the parent level in the classification hierarchy.  For example if this plantConcept were at the genus level the plantParent would be the plantConcept that is the family level (or subfamily level).</attDefinition>
		</attribute>
		<attribute>
			<attName>plantDescription</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(600)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The plantDescription is a description of the plantConcept by the party contributing the plantConcept.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotplotContributor.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	
<title>Prototype Veg Plots Database Component Description: 
    plotContributor</title>
<author>John Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>

<entity>
	<entityName>vegPlot.PLOTCONTRIBUTOR</entityName>
	<entitySummary>This table stores information about a party contributing to
 a vegetation plot.</entitySummary>
	<entityDescription>This table serves as an interesection entity used to 
'link' a party with a specific vegetation plot. </entityDescription>
	<attribute> 
		<attName>plotContributor_id </attName>
		<attNulls>No </attNulls>	
		<attType>NUMBER </attType>
		<attKey>P</attKey>
		<attNotes>n/a</attNotes>
		<attReferences>n/a</attReferences>
		<attDefinition>Database assigned value for a party contributing to a 
            vegetation plot. </attDefinition>
	</attribute>



	<attribute>
                <attName>plot_id </attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>F</attKey>
                <attReferences>PLOT</attReferences>
                <attNotes>This is the foreign key into the plot table. </attNotes>
                <attDefinition>Database assigned value for a given plot 
this is a link to the project entity. </attDefinition>
        </attribute>

	<attribute>
                <attName>party_id</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>F </attKey>
                <attReferences>PARTY </attReferences>
                <attNotes>This is the foreign key into the PARTY table.</attNotes>
                <attDefinition>Database assigned value for a given party this is a link to 
            the party entity. </attDefinition>
        </attribute>

	<attribute>
                <attName>roleCode</attName>
                <attNulls>No </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>The role that a specific party (party_id) had in the 
            plot collection - this can include such roles as 
            PI, contact, author, etc.  This will be linked to an 
            entity named: </attDefinition>
        </attribute>


	<children> PARTY </children>
</entity>
</dataModel>
