=== NCEAS/vegbank/docs/tableStructure.dtd
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!ENTITY % Boolean "(true | false) 'false'">
<!ELEMENT dataModel (title, author, institution, contributor, description, date, entity)>
<!ELEMENT entity (entityName*, entitySummary*, entityDescription*, module, attribute*, children*, childrenRef*)>
<!ELEMENT attribute (attName, attNulls, attType, attKey, attReferences, attNotes, attDefinition, defaultValue*, TVCompliant*, TVName*, businessRules*)>
<!ELEMENT businessRules (constraintAttribute | required | (minCharacterLength | maxCharacterLength)* | (minNumericValue, maxNumericValue))>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT contributor (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT entityName (#PCDATA)>
<!ELEMENT entitySummary (#PCDATA)>
<!ELEMENT entityDescription (#PCDATA)>
<!ELEMENT attName (#PCDATA)>
<!ELEMENT attNulls (#PCDATA)>
<!ELEMENT attType (#PCDATA)>
<!ELEMENT attKey (#PCDATA)>
<!ELEMENT attReferences (#PCDATA)>
<!ELEMENT attNotes (#PCDATA)>
<!ELEMENT attDefinition (#PCDATA)>
<!ELEMENT TVCompliant (#PCDATA)>
<!ELEMENT TVName (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT children (#PCDATA)>
<!ELEMENT childrenRef (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT constraintAttribute (#PCDATA)>
<!ELEMENT minCharacterLength (#PCDATA)>
<!ELEMENT maxCharacterLength (#PCDATA)>
<!ELEMENT minNumericValue (#PCDATA)>
<!ELEMENT maxNumericValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!-- -->

=== NCEAS/vegbank/docs/xml/commtaxa/commTaxaCommReference.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: commReference</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>7 February 2002</date>
	<entity>
		<entityName>commTaxa.commReference</entityName>
		<entitySummary>This table stores references which are linked to community concepts.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>COMMREFERENCE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the commReference table.</attDefinition>
		</attribute>
		<attribute>
			<attName>authors</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(200)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Names of authors as they appear within the entity being cited. </attDefinition>
		</attribute>
		<attribute>
			<attName>title</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(200)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Name by which the cited resource is known. </attDefinition>
		</attribute>
		<attribute>
			<attName>pubDate </attName>
			<attNulls>Yes</attNulls>
			<attType>DATE </attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Date the citation was published. </attDefinition>
		</attribute>
		<attribute>
			<attName>edition </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Version of the cited resource. </attDefinition>
		</attribute>
		<attribute>
			<attName>seriesName </attName>
			<attNulls>Yes  </attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Name of a series. </attDefinition>
		</attribute>
		<attribute>
			<attName>issueIdentification </attName>
			<attNulls>Yes </attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Information identifying the issue of the series. </attDefinition>
		</attribute>
		<attribute>
			<attName>otherCitationDetails </attName>
			<attNulls>Yes </attNulls>
			<attType>VARCHAR(100)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Other information required for a complete citation, like a URL. </attDefinition>
		</attribute>
		<attribute>
			<attName>page </attName>
			<attNulls>Yes </attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Page of the book or serial where the article appears. </attDefinition>
		</attribute>
		<attribute>
			<attName>tableCited</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>name/number of published table containing community name, or an entity name if in an archival database.</attDefinition>
		</attribute>
		<attribute>
			<attName>ISBN </attName>
			<attNulls>Yes </attNulls>
			<attType>VARCHAR(20) </attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>International Standard Book Number. </attDefinition>
		</attribute>
		<attribute>
			<attName>ISSN </attName>
			<attNulls>Yes </attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>International Standard Serial Number. </attDefinition>
		</attribute>
		<attribute>
			<attName>commDescription</attName>
			<attNulls>Yes</attNulls>
			<attType>TEXT</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Description of the community. Used where the commReference table record serves as a self reference for purposes of establishing a community concept (community assertion).</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/vegplot/vegPlotNote.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: note</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>31October 2001</date>
	<entity>
		<entityName>vegPlot.Note</entityName>
		<entitySummary>This table is where notations associated with table records are stored</entitySummary>
		<entityDescription>All notes associated with plots and plot observations are stored in this table.  These notes can be linked to any table, record and attribute via the noteLink table.</entityDescription>
		<attribute>
			<attName>NOTE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary key for the note table</attNotes>
			<attDefinition>Database generated identifier assigned to each unique note. </attDefinition>
		</attribute>
		<attribute>
			<attName>NOTELINK_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>noteLink.NOTELINK_ID</attReferences>
			<attNotes>Foreign key into the notelink table</attNotes>
			<attDefinition>Link to the noteLink table via which a note is associated with a table, record and attribute.</attDefinition>
		</attribute>
		<attribute>
			<attName>PARTY_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>party.PARTY_ID</attReferences>
			<attNotes>Foreign key into the party table</attNotes>
			<attDefinition>Link to the party table to identify the party that contributed the note.</attDefinition>
		</attribute>
		<attribute>
			<attName>ROLE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>aux_Role.ROLE_ID</attReferences>
			<attNotes>Foreign key into the aux_role table</attNotes>
			<attDefinition>What role was the party palying when the note was applied?</attDefinition>
		</attribute>
		<attribute>
			<attName>noteDate</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>The date on which the note was stored in the database.</attDefinition>
		</attribute>
		<attribute>
			<attName>noteType</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>The type of note:  Database Management, Observation Author, Database User and Internal.  "Database Managment" notes are those added by the management team and may be queried and viewed by the public. "Database Use" notes are those entered by the users of the database and are publicly viewable.  "Internal" notes are for management to use internally and will not be broadcast.
</attDefinition>
		</attribute>
		<attribute>
			<attName>noteText </attName>
			<attNulls>No</attNulls>
			<attType>TEXT</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>actual note text</attNotes>
			<attDefinition>The text of the note.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotCoverMethod.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	


<title> Prototype Veg Plots Database Component Description: cover method</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description>This table specifies the cover scale recognized by the plot data collectors.</description>
<date></date>

<entity>
	<entityName>vegPlot.CoverMethod </entityName>
	<entitySummary>This table links the cover scale recognized by the plot data collectors
	to a cover scale specified in the coverIndicies table. </entitySummary>
	<entityDescription> </entityDescription>

        <attribute>
                <attName>COVERMETHOD_ID</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>PK </attKey>
		<attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Primary Key for the coverMethod table.</attDefinition>
        </attribute>

	
        <attribute>
                <attName>CITATION_ID</attName>
                <attNulls>Yes</attNulls>
                <attType>NUMBER </attType>
                <attKey>FK</attKey>
		<attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Foreign Key into the citation table, linking a reference
		to a cover method.</attDefinition>
        </attribute>

	<attribute> 
		<attName>coverType</attName>
		<attNulls>No </attNulls>	
		<attType>NUMBER </attType>
		<attKey>n/a </attKey>
		<attReferences>n/a </attReferences>
		<attNotes>Name of the cover method.</attNotes>
		<attDefinition>Cover scale type (examples may include: Braun-Blanquet scale, the Barkman et al., Franklin et al., Pfister-Arnold etc..</attDefinition>
	</attribute>



	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotGlobalInference.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	

<title> Prototype Veg Plots Database Component Description: globalInference</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>



<entity>
	<entityName>vegPlot.globalInference</entityName>
	<entitySummary>This table stores information about the area used to infer 
	characteristics of plants which are common in size.</entitySummary>
	<entityDescription> </entityDescription>
	<attribute> 
		<attName>GLOBALINFERENCE_ID</attName>
		<attNulls>No</attNulls>	
		<attType>NUMBER </attType>
		<attKey>PK</attKey>
		<attReferences>n/a </attReferences>
		<attNotes>Primary key for globalInference table. </attNotes>
		<attDefinition>Database assigned value to each unique record in 
		the globalInference table. </attDefinition>
	</attribute>



	<attribute>
                <attName>OBS_ID</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>FK</attKey>
                <attReferences>vegPlotParty </attReferences>
                <attNotes>Foreign key into the plotObservation table. </attNotes>
                <attDefinition>n/a</attDefinition>
        </attribute>


	<attribute>
                <attName>globalInferenceArea</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>n/a</attKey>
		<attReferences>n/a </attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This is the inference area used to characterize 
		the plants of the same dimensions.  These dimensions are defined 
		in the inferenceClassIndex table and may be characterized be either 
		height or diameter.</attDefinition>
        </attribute>



	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotTreeStem.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: treeStem</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>23 Sep 2001</date>
	<entity>
		<entityName>vegPlot.treeStem</entityName>
		<entitySummary>This table is intended to store information about indivdual tree stem data collected during a plot observation event.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>STEM_ID</attName>
			<attNulls>No </attNulls>
			<attType>INT</attType>
			<attKey>PK </attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary Key for the stemData table.</attNotes>
			<attDefinition>Database generated identifier assigned to each unique stem observation. </attDefinition>
		</attribute>
		<attribute>
			<attName>TAXONOBSERVATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>taxonObservation.TAXONOBSERVATION_ID</attReferences>
			<attNotes>Foreign key into the taxonObservation table</attNotes>
			<attDefinition>Foreign key into the taxonObservation table, thereby associating a taxon identification with the tree stem(s).</attDefinition>
		</attribute>
		<attribute>
			<attName>stemCode</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Name or code applied to a specific stem in the plot. This is generally a numeric label to associate a fielddata entry with a stem in the database.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemDiameter</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(5,1)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The diameter of the stem in centimeters. When diameter classes are used the the stemDiameter is the midpoint between the low end and high end for the diameter class;  the offset between this and the endpoints is stored in the stemDiameterAccuracy attribute.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemDiameterAccuracy</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMBER(2,1)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The accuracy of the stem diameter measurements in centimeters. This represents the distance between the diameter class midpoint and endpoint.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemXPosition</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMBER(3,2)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a </attReferences>
			<attNotes/>
			<attDefinition>The X-coordinate of the stem position. The user will enter the relative position of stems with respect to the plot origin (in meters) with the x-axis defined by the plot azimuth.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemYPosition</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMBER(3,2)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The Y-coordinate of the stem position, as above.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemHeight</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMBER(3,2)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The measured height of the stem in meters. When height classes were used the stemHeight is the midpoint between the low end and high end for the height class; the offset between this and the endpointsis stored in the stemHeightAccuracy field.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemHeightAccuracy</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMBER(2,2)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The accuracy of the measured height of a stem, being the offset between the midpoint of the class and the endpoint, in meters.</attDefinition>
		</attribute>
		<attribute>
			<attName>stemCount</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>The default value is 1.  This field is not logically necessary, but allows for more compact entry and storage of tree stem tally data.</attNotes>
			<attDefinition>The number of stems of a single species that have a common stem diameter and lack height and location data.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotPlotObservation.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	
<title> Prototype Veg Plots Database Component Description: plotObservation</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date>Wed Sep 27 09:06:55 PDT 2000 </date>

<entity>
	<entityName>vegPlot.PLOTOBSERVATION</entityName>
	<entitySummary>This table stores plot information that may vary between sampling events.</entitySummary>
	<entityDescription>Recognizing that a plot may be resampled and that some of the environmental
	conditions may change between resampling events the database design has changed to accomodate this.  
	Now all attributes that are percieved to potentially change on the order of a decade are stored in the 
	plotObservation table whereas those attributes deemed to be regular in time/space are stored in the plot 
	table.
	</entityDescription>
	<attribute> 
		<attName>obs_id </attName>
		<attNulls>No</attNulls>	
		<attType>NUMBER</attType>
		<attKey>P</attKey>
		<attNotes>n/a </attNotes>
		<attDefinition>This is an internal database identifier assigned to each unique observation. </attDefinition>
	</attribute>



	<attribute>
                <attName>parentPlot</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>F</attKey>
                <attReferences>PLOT</attReferences>
                <attNotes>Foreign key into the plot table.</attNotes>
                <attDefinition>This represents the link between an observation plot location. </attDefinition>
        </attribute>


	<attribute>
                <attName>previousObs</attName>
                <attNulls>Yes</attNulls>
                <attType>NUMBER</attType>
                <attKey>F</attKey>
                <attReferences>PLOTOBSERVATION</attReferences>
                <attNotes>Recursive foreign key which points to the previous observation in this area</attNotes>
                <attDefinition>This is the plot observtion that was previously made at this plot location.  If observations at a plot are made every year then this key points to the observation number that corresponds to the observation made the year before.</attDefinition>
        </attribute>
<attribute>
                <attName>authorObsCode</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>This is the code that the author uses to identify this observation.</attDefinition>
        </attribute>
<attribute>
                <attName>plotStartDate</attName>
                <attNulls>Yes</attNulls>
                <attType>DATE</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>Attribute added at the September meeting at NCEAS.</attNotes>
                <attDefinition>If the observation takes more than a single day then this is the first day in which observations were made.</attDefinition>
        </attribute>
<attribute>
                <attName>plotEndDate</attName>
                <attNulls>Yes</attNulls>
                <attType>DATE</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>Attribute added at the September meeting at NCEAS.</attNotes>
                <attDefinition>If the observation takes more than a single day then this is the last day in which observations were made. </attDefinition>
        </attribute>
<attribute>
                <attName>dateAcc</attName>
                <attNulls>Yes</attNulls>
                <attType>NUMBER</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>Added at the September meeting at NCEAS. </attNotes>
                <attDefinition>Estimated Accuracy of the observation date.</attDefinition>
        </attribute>
<attribute>
                <attName>effortLevel</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>Use pick list; 
                                 1) Very thorough 
                                 2) Average effort 
                                 3) Hurried description;
                                some less common
                                species may have been
                                missed.</attNotes>
                <attDefinition>This is the effort spent making the observations as estimated by the data collector.</attDefinition>
        </attribute>

	
	<children>taxonObservations, communityType</children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotClassContributor.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: classContributor</title>
	<author>John Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>23 Sept 2001</date>
	<entity>
		<entityName>vegPlot.classContributor</entityName>
		<entitySummary>This table stores information about who participated in a classification event</entitySummary>
		<entityDescription>This table serves as an interesection entity used to link a party with
a specific plot classification event.</entityDescription>
		<attribute>
			<attName>CLASSCONTRIBUTOR_ID </attName>
			<attNulls>No </attNulls>
			<attType>NUMBER </attType>
			<attKey>PK </attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary key for the classContributor table.</attNotes>
			<attDefinition>Database generated identifier assigned to each unique contribution to the classificaiton of a plot observation. </attDefinition>
		</attribute>
		<attribute>
			<attName>COMMCLASS_ID</attName>
			<attNulls>No </attNulls>
			<attType>NUMBER </attType>
			<attKey>FK </attKey>
			<attReferences>commClass.COMMCLASS_ID</attReferences>
			<attNotes>Foreign key into the commClass table.</attNotes>
			<attDefinition>Observation classification event to which the contributor is associated.   </attDefinition>
		</attribute>
		<attribute>
			<attName>PARTY_ID</attName>
			<attNulls>No </attNulls>
			<attType>NUMBER </attType>
			<attKey>FK </attKey>
			<attReferences>party.PARTY_ID </attReferences>
			<attNotes>Foreign key into the party table.</attNotes>
			<attDefinition>Link to the party that contributed to the classificaiton event.</attDefinition>
		</attribute>
		<attribute>
			<attName>roleCode </attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(30)</attType>
			<attKey>n/a </attKey>
			<attReferences>n/a </attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>The role that the party had in the classification event (e.g., classifier, consultant, research advisor). </attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/vegplot/vegPlotUserDefined.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: userDefined </title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>31 October 2001</date>
	<entity>
		<entityName>vegPlot.userDefined </entityName>
		<entitySummary/>
		<entityDescription>This table contains the definitions of user-defined variables.  The table structure stems from desire to keep the user-defined variables separate from the main body of the database.  </entityDescription>
		<attribute>
			<attName>USERDEFINED_ID</attName>
			<attNulls>No </attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary key for userDefined</attNotes>
			<attDefinition>Database generated identifier assigned to each unique user-defined variable. </attDefinition>
		</attribute>
		<attribute>
			<attName>userDefinedName</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(30)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>open list</attNotes>
			<attDefinition>Name of the user-defined variable.</attDefinition>
		</attribute>
		<attribute>
			<attName>userDefinedMetadata</attName>
			<attNulls>Yes</attNulls>
			<attType>TEXT</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Metadata about this user-defined variable.</attDefinition>
		</attribute>
		<attribute>
			<attName>userDefinedCategory</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(30)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>Category of variable; included to facilitate queries for specific types of data.</attDefinition>
		</attribute>
		<attribute>
			<attName>userDefinedType</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(20)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Database data type of the user-defined variable.</attDefinition>
		</attribute>
		<attribute>
			<attName>tableName</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(50)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a </attNotes>
			<attDefinition>Name of table with which this user-defined variable is associated.  For example soilBHorizonColor may be defined by the data contributor as associated with the observation table.</attDefinition>
		</attribute>
		<children>definedValue</children>
	</entity>
</dataModel>
