=== NCEAS/vegbank/docs/tableStructure.dtd
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!ENTITY % Boolean "(true | false) 'false'">
<!ELEMENT dataModel (title, author, institution, contributor, description, date, entity)>
<!ELEMENT entity (entityName*, entitySummary*, entityDescription*, module, attribute*, children*, childrenRef*)>
<!ELEMENT attribute (attName, attNulls, attType, attKey, attReferences, attNotes, attDefinition, defaultValue*, TVCompliant*, TVName*, businessRules*)>
<!ELEMENT businessRules (constraintAttribute | required | (minCharacterLength | maxCharacterLength)* | (minNumericValue, maxNumericValue))>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT contributor (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT entityName (#PCDATA)>
<!ELEMENT entitySummary (#PCDATA)>
<!ELEMENT entityDescription (#PCDATA)>
<!ELEMENT attName (#PCDATA)>
<!ELEMENT attNulls (#PCDATA)>
<!ELEMENT attType (#PCDATA)>
<!ELEMENT attKey (#PCDATA)>
<!ELEMENT attReferences (#PCDATA)>
<!ELEMENT attNotes (#PCDATA)>
<!ELEMENT attDefinition (#PCDATA)>
<!ELEMENT TVCompliant (#PCDATA)>
<!ELEMENT TVName (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT children (#PCDATA)>
<!ELEMENT childrenRef (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT constraintAttribute (#PCDATA)>
<!ELEMENT minCharacterLength (#PCDATA)>
<!ELEMENT maxCharacterLength (#PCDATA)>
<!ELEMENT minNumericValue (#PCDATA)>
<!ELEMENT maxNumericValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!-- -->

=== NCEAS/vegbank/docs/xml/planttaxa/plantTaxaPlantName.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: plantName</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>7 February 2002</date>
	<entity>
		<entityName>plantTaxa.plantName</entityName>
		<entitySummary>This table stores plant names</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>PLANTNAME_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the plantName table.</attDefinition>
		</attribute>
		<attribute>
			<attName>plantName</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(500)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The plant name.</attDefinition>
		</attribute>
		<attribute>
			<attName>plantNameWithAuthor</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(100)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The plant name with any with author notation embedded </attDefinition>
		</attribute>
		<attribute>
			<attName>PLANTREFERENCE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>plantReference.PLANTREFERENCE_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Foreign key into the plantReference table to identify the original source of the name (usually the type description).</attDefinition>
		</attribute>
		<attribute>
			<attName>dateEntered</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Field stores the date that the name was entered into the database.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotTaxonObservation.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: taxonObservation </title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>23 Sep 2001</date>
	<entity>
		<entityName>taxonObservation</entityName>
		<entitySummary>This table contains the author's determination of a taxon and the overal cover of that taxon.</entitySummary>
		<entityDescription>This table stores information about the original identification of the author of the plot and the taxonomic authority used by that author (i.e. a name - citation pair constituting a taxnomic concept).  The table also contains a record of cumulative cover (cover across all strata) of the taxon when not divided into strata.</entityDescription>
		<attribute>
			<attName>TAXONOBSERVATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary key of the table.</attNotes>
			<attDefinition>Database generated identifier assigned to each unique observation of a taxon in a plot. </attDefinition>
		</attribute>
		<attribute>
			<attName>OBSERVATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>observation.OBSERVATION_ID</attReferences>
			<attNotes>Foreign key into the plotObservation table.</attNotes>
			<attDefinition>Link to the parent observation event of this taxonl observation.</attDefinition>
		</attribute>
		<attribute>
			<attName>TAXONNAME_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>taxonName.TAXONNAME_ID</attReferences>
			<attNotes>Foreign key into taxonName table. </attNotes>
			<attDefinition>The taxon name that the author of the plot used to refer to a taxon observed within the plot. </attDefinition>
		</attribute>
		<attribute>
			<attName>TAXONREFERENCE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>taxonReference.TAXONREFERENCE_ID</attReferences>
			<attNotes>Foreign key into the taxonReference table.</attNotes>
			<attDefinition>The authority for the taxon that was used by the plot author.  If the authority is unknown  the author of the plot is the authority. For other than legacy data, this field plus taxonName_ID will be sufficient to determine taxonInterpretation.taxonConcept_ID.</attDefinition>
		</attribute>
		<attribute>
			<attName>taxonCollection</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(100)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Specifics about the location of a collection made of the taxon</attDefinition>
		</attribute>
		<attribute>
			<attName>taxonCover</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(3,2)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>(could be calculated)</attNotes>
			<attDefinition>Overall cover of the taxon across all strata</attDefinition>
		</attribute>
		<attribute>
			<attName>taxonBasalArea</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(3,5)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Total basal area of the species in the stemInferenceArea in m2/ha</attDefinition>
		</attribute>
		<attribute>
			<attName>taxonInferenceArea</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(5,3)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>The area used to infer the coverage of the taxon, if not the same as observation.taxonInferenceArea.</attNotes>
			<attDefinition>This is the area in m2 used to infer the cover of a given taxon.  Generally this should be equal to observation.taxonInferenceArea, but at times this area may be larger or smaller.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotParty.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	
<title> Prototype Veg Plots Database Component Description: party</title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>




	<entity>
	<entityName>vegPlot.PARTY </entityName>
	<entitySummary>This table stores information relevent to a party which may be either an individual or an organization.</entitySummary>
	<entityDescription> </entityDescription>
	

<attribute>
                <attName>party_id</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>P</attKey>
                <attNotes>Primary key for PARTY table.</attNotes>
                <attDefinition> Database assigned value that is
                                                 unique to each party
                                                 contributing in the collection of
                                                 plots.
		</attDefinition>

        </attribute>
        
                
                
        <attribute>
                <attName>salutation</attName>
                <attNulls>yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>Salutation preceding one's given name.</attDefinition>
        </attribute>

<attribute>
                <attName>givenName</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a</attKey>
                <attNotes>n/a</attNotes>
                <attDefinition>One's first name.</attDefinition>
        </attribute>
        
                
                
        <attribute>
                <attName>surName </attName>
                <attNulls>No </attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a</attNotes>
                <attDefinition>Name shared in common to identify the members of a family, as distinguished from each member's given name.</attDefinition>
        </attribute>
<attribute>
                <attName>organizationName</attName>
                <attNulls>No</attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
                <attNotes>n/a </attNotes>
                <attDefinition>Name of an organization. </attDefinition>
        </attribute>
        
                
                
        <attribute>
                <attName>positionName</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Name of one's position. </attDefinition>
        </attribute>
<attribute>
                <attName>hoursOfService</attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a </attKey>
                <attNotes>n/a </attNotes>
                <attDefinition>Hours in which one may contact the party. </attDefinition>
        </attribute>
        
                
                
        <attribute>
                <attName>contactInstructions </attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
                <attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Instructions for contacting a party. </attDefinition>
        </attribute>
	



	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotInterpretation.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	
<title> Prototype Veg Plots Database Component Description: Interpretation </title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description> </description>
<date></date>

<entity>
	<entityName>vegPlot.INTERPRETATION </entityName>
	<entitySummary>This table was designed to allow users other than the author of the plot to interpret taxon names and authorities used to describe a population. </entitySummary>
	<entityDescription>The development of this table was initiated at the working group meeting at NCEAS in September 2000.  The desire to re-interpret the taxon names used by the plot author was realized and this table subsequently initiated.</entityDescription>
	<attribute> 
		<attName>interpretation_Id</attName>
		<attNulls>No</attNulls>	
		<attType>NUMBER</attType>
		<attKey>PK</attKey>
		<attReferences>n/a</attReferences>
		<attNotes>Primary key for the interpretation table.</attNotes>
		<attDefinition>Database assigned value for a unique interpretation of a taxon used in a plot observation.</attDefinition>
	</attribute>

        <attribute>
                <attName>party_id </attName>
                <attNulls>No</attNulls>
                <attType>NUMBER</attType>
                <attKey>FK </attKey>
                <attReferences>PARTY </attReferences>
                <attNotes>Foreign key into the party table. </attNotes>
                <attDefinition>This key links a party to an interpretation. </attDefinition>
        </attribute>
        <attribute>
                <attName>taxonObservation_Id</attName>
                <attNulls>No</attNulls>
                <attType>NUMBER </attType>
                <attKey>FK</attKey>
                <attReferences>taxonObservation </attReferences>
                <attNotes>Foreign key into the taxonObservation table. </attNotes>
                <attDefinition>This key 'links' the interpretation to a particular taxon recognized in a plot. </attDefinition>
        </attribute>

	
	<!-- below added on Oct 18 -->
	<attribute>
                <attName>taxonName</attName>
                <attNulls>No</attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>This is the name applied to the vegetation by the interpreter which
		will be used, along with the authority, to look up the current circumscription from the 
		HDMS or a local instance of a plant taxa database.</attDefinition>
        </attribute>

	<attribute>
                <attName>authority </attName>
                <attNulls>No </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>This is the authority that the interpreter is following when he/she applies the
		above taxon to a plant.  This, along with the taxon name and some date information, will be used to look up the current circumscription from the 
		HDMS or a local instance of a plant taxa database.</attDefinition>
        </attribute>
	
	<attribute>
                <attName>usageStartDate </attName>
                <attNulls>No </attNulls>
                <attType>Date </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>This is the date that the authority started using the above taxon name. </attDefinition>
        </attribute>

	<attribute>
                <attName>usageStopDate </attName>
                <attNulls>No </attNulls>
                <attType>Date </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>This may be too detailed information to really expect to include, although it is
		required to lookup a circumscription from the plant taxa database.  Maybe a single date would work, where the 
		date was a point in time when the authority was using the taxon name.</attNotes>
                <attDefinition>This is the date that the authority stopped using the above taxon name. </attDefinition>
        </attribute>
	

	<!-- above added on Oct 18 -->
        <attribute>
                <attName>circum_id</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>FK</attKey>
                <attReferences>plantTaxa.CIRCUMSCRIPTION </attReferences>
                <attNotes>This is the foreign key into the plantTaxa or HDMS database, that will store the 
		circumscription corresponding to the re-interpretaion of the taxon.</attNotes>
                <attDefinition>Circumscription number updated from the plant taxa database. </attDefinition>
        </attribute>
        <attribute>
                <attName>role </attName>
                <attNulls>No </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>This is the role of the party making the interpretation.  Expected values may be: author, interpreter. </attDefinition>
        </attribute>
        <attribute>
                <attName>interpretationDate</attName>
                <attNulls>No </attNulls>
                <attType>DATE </attType>
                <attKey>n/a </attKey>
                <attReferences>n/a </attReferences>
                <attNotes>This is the date that the interpretation was made. </attNotes>
                <attDefinition> </attDefinition>
        </attribute>


	<attribute>
                <attName>notes </attName>
                <attNulls>Yes </attNulls>
                <attType>VARCHAR2 </attType>
                <attKey>n/a </attKey>
                <attReferences>n/a </attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>These are the notes that the interpreter would like to include with the interpretation. </attDefinition>
        </attribute>


	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/commtaxa/commTaxaCommName.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Vegetation Plots Database Component Description: commName</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>7 February 2002</date>
	<entity>
		<entityName>commTaxa.commName</entityName>
		<entitySummary>This table stores vegetation community names</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>COMMNAME_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the commName table.</attDefinition>
		</attribute>
		<attribute>
			<attName>commName</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(500)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>The community name.</attDefinition>
		</attribute>
		<attribute>
			<attName>COMMREFERENCE_ID</attName>
			<attNulls>Yes</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>commReference.COMMREFERENCE_ID</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Foreign key into commReference to identify the source of the name.</attDefinition>
		</attribute>
		<attribute>
			<attName>dateEntered</attName>
			<attNulls>Yes</attNulls>
			<attType>DATE</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Field stores the date that the name was entered into the database.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/vegPlotCommunityUsage.xml
<?xml version="1.0"?>
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">

<dataModel>	


<title> Prototype Veg Plots Database Component Description: communityUsage </title>
<author>J. Harris </author>
<institution>NCEAS </institution>
<contributor> </contributor>
<description>This table stores information about the vegetation classification applied to a specific plotObservation 
by a specific party.</description>
<date></date>

<entity>
	<entityName>vegPlot.communityUsage </entityName>
	<entitySummary>This table tracks the application of vegetation community names to plot observations by 
	differing parties over time.</entitySummary>
	<entityDescription> </entityDescription>

        <attribute>
                <attName>COMMUNITYUSAGE_ID</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>PK </attKey>
		<attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Primary Key for the communityUsage table.</attDefinition>
        </attribute>


	<attribute> 
		<attName>PARTY_ID</attName>
		<attNulls>No </attNulls>	
		<attType>NUMBER </attType>
		<attKey>FK </attKey>
		<attReferences>PARTY </attReferences>
		<attNotes>Foreign key into the party table.</attNotes>
		<attDefinition>This key links the application of a veg class to a plot by a given party identified by this key. </attDefinition>
	</attribute>



	<attribute>
                <attName>OBS_ID</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>FK</attKey>
                <attReferences>plotObservation</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Foreign Key into the plotObservation table. </attDefinition>
        </attribute>

	<attribute>
                <attName>COMMUNITYTYPE_ID</attName>
                <attNulls>No </attNulls>
                <attType>NUMBER </attType>
                <attKey>FK</attKey>
                <attReferences>communityType</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Foreign Key into the communityType table. </attDefinition>
        </attribute>
	
	<attribute>
                <attName>type</attName>
                <attNulls>No </attNulls>
                <attType>BOOLEAN </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Specifies if the plot observation was used in defining the classification type.</attDefinition>
        </attribute>
	
	<attribute>
                <attName>startDate</attName>
                <attNulls>No </attNulls>
                <attType>DATE </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Start date for the application of a vegetation class to a plot observation by a given party. </attDefinition>
        </attribute>
	
	<attribute>
                <attName>stopDate</attName>
                <attNulls>No </attNulls>
                <attType>DATE </attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>Stop date for the application of a vegetation class to a plot observation by a given party.</attDefinition>
        </attribute>
	
	<attribute>
                <attName>classQuality</attName>
                <attNulls>Yes</attNulls>
                <attType>VARCHAR2</attType>
                <attKey>n/a</attKey>
                <attReferences>n/a</attReferences>
                <attNotes>n/a </attNotes>
                <attDefinition>This attribute is to store the classification quality associated with 
		the community usage.  Although it is pretty subjective field it is meaningful in many
		 cases and would be bad to lose the record. </attDefinition>
        </attribute>
	
	

	<children> </children>
</entity>
</dataModel>

=== NCEAS/vegbank/docs/xml/vegplot/vegPlotDisturbanceObs.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title> Vegetaton Plots Database Component Description:disturbanceObs</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor>R.K. Peet</contributor>
	<description/>
	<date>31 October 2001</date>
	<entity>
		<entityName>vegPlot.disturbanceObs</entityName>
		<entitySummary>This table stores plot observation information pertaining toobserver estamation of the disturbance history of the plot. </entitySummary>
		<entityDescription>disturbanceObs is  a child of observation; a plot might experience many types of disturbance unique to different observation events.</entityDescription>
		<attribute>
			<attName>disturbanceObs</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>Primary key for disturbanceObs</attNotes>
			<attDefinition>Database generated identifier assigned to each unique disturbance observation..</attDefinition>
		</attribute>
		<attribute>
			<attName>OBSERVATION_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>FK</attKey>
			<attReferences>observation.OBSERVATION_ID</attReferences>
			<attNotes>Foreign key that points to the parent observation for this disturbance record</attNotes>
			<attDefinition>Link to the observation event with which this report of a disturbance event is associated.</attDefinition>
		</attribute>
		<attribute>
			<attName>disturbanceType</attName>
			<attNulls>No</attNulls>
			<attType>VARCHAR(30)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>The type of disturbance being reported</attDefinition>
		</attribute>
		<attribute>
			<attName>disturbanceIntensity</attName>
			<attNulls>Yes</attNulls>
			<attType>VARCHAR(30)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>closed list</attNotes>
			<attDefinition>Intensity or degree of the disturbance. </attDefinition>
		</attribute>
		<attribute>
			<attName>diosturbanceAge</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(4,2)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Estimated time in years since the disturbance event.</attDefinition>
		</attribute>
		<attribute>
			<attName>disturbanceExtent</attName>
			<attNulls>Yes</attNulls>
			<attType>NUMERIC(3,0)</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Percent of the plot that experienced the event.</attDefinition>
		</attribute>
		<attribute>
			<attName>disturbanceComment</attName>
			<attNulls>Yes</attNulls>
			<attType>TEXT</attType>
			<attKey>n/a</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Text description of details of the disturbance and its impact on the vegetation.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>

=== NCEAS/vegbank/docs/commTaxaCommLineage.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Robert K. Peet (private) -->
<!DOCTYPE dataModel SYSTEM "tableStructure.dtd">
<dataModel>
	<title>Prototype Veg Plots Database Component Description: commLineage</title>
	<author>J. Harris </author>
	<institution>NCEAS </institution>
	<contributor/>
	<description/>
	<date/>
	<entity>
		<entityName>comm.commLineation</entityName>
		<entitySummary>This table stores tracks the lineage of vegetation community 
concepts.</entitySummary>
		<entityDescription/>
		<attribute>
			<attName>LINEAGE_ID</attName>
			<attNulls>No</attNulls>
			<attType>INT</attType>
			<attKey>PK</attKey>
			<attReferences>n/a</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>Database assigned value to each unique record in the commLineage table.</attDefinition>
		</attribute>
		<attribute>
			<attName>CONCEPT1_ID</attName>
			<attNulls>NO</attNulls>
			<attType>INT</attType>
			<attKey>n/a</attKey>
			<attReferences>commConcept</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the foreign key into the commConcept table 
"pointing" to the child concept.</attDefinition>
		</attribute>
		<attribute>
			<attName>CONCEPT2_ID</attName>
			<attNulls>NO</attNulls>
			<attType>INT</attType>
			<attKey>n/a</attKey>
			<attReferences>commConcept</attReferences>
			<attNotes>n/a</attNotes>
			<attDefinition>This is the foreign key into the commConcept table 
"pointing" to the parent concept.</attDefinition>
		</attribute>
		<children/>
	</entity>
</dataModel>
