=== NCEAS/vegbank/veg_plot/exp/database_access/vegPlot2001cv.dtd
<!ENTITY % Boolean "(true | false) 'false'">
<!--
  * vegPlot20001cv.dtd
  *
  *      Authors: John Harris
  * Organization: National Center for Ecological Analysis and Synthesis
  *    Copyright: 2000 Regents of the University of California and the
  *               National Center for Ecological Analysis and Synthesis
  *  For Details: http://www.nceas.ucsb.edu/
  *      Created: April 2001
  *
  * This DTD describes the structure and content of XML documents used
  * to represent, store, and exchange a single vegetation plot or a subset 
	* of the vegetation plot
  *
-->


<!ELEMENT vegPlot (project)>

<!ELEMENT project (projectName, projectDescription, plot, projectContributor)>
<!ELEMENT projectName (#PCDATA)> 
<!ELEMENT projectDescription (#PCDATA)>

<!ELEMENT plot (plotId*, authorPlotCode, parentPlot*, plotType*, samplingMethod*, 
	coverScale*, origLat*, origLong*, plotShape*, plotSize*, plotSizeAcc*, 
	elevationValue*, altPosAcc*, slopeAspect*, slopeGradient*,
	slopePosition*, hydrologicRegime*, soilDrainage*, surfGeo*, plotObservation*, 
	namedPlace*, stand*, graphic*, plotContributor*, topoPosition*, elevationValue*,
	xCoord*, yCoord*, coordType*, soilDepth*, soilType*, 
	percentRockGravel*, perSmallRx*, perSand*, perLitter*, perWood*, perBareSoil*,
	leafPhenology*, importSource*)>
	
	<!ELEMENT plotId (#PCDATA)>
 	<!ELEMENT authorPlotCode (#PCDATA)>
	<!ELEMENT parentPlot (#PCDATA)>
	<!ELEMENT plotType (#PCDATA)>
	<!ELEMENT samplingMethod (#PCDATA)>
	<!ELEMENT coverScale (#PCDATA)>
	<!ELEMENT origLat (#PCDATA)>
	<!ELEMENT origLong (#PCDATA)>
	<!ELEMENT plotShape (#PCDATA)>
	<!ELEMENT plotSize (#PCDATA)>
	<!ELEMENT plotSizeAcc (#PCDATA)>
	<!ELEMENT altValue (#PCDATA)>
	<!ELEMENT altPosAcc (#PCDATA)>
	<!ELEMENT slopeAspect (#PCDATA)>
	<!ELEMENT slopeGradient (#PCDATA)>
	<!ELEMENT slopePosition (#PCDATA)>
	<!ELEMENT hydrologicRegime (#PCDATA)>
	<!ELEMENT soilDrainage (#PCDATA)>
	<!ELEMENT surfGeo (#PCDATA)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT currentCommunity  (#PCDATA)>
	<!ELEMENT topoPosition  (#PCDATA)>
	<!ELEMENT elevationValue  (#PCDATA)>
	<!ELEMENT xCoord  (#PCDATA)>
	<!ELEMENT yCoord  (#PCDATA)>
	<!ELEMENT coordType  (#PCDATA)>
	<!ELEMENT soilDepth  (#PCDATA)>
	<!ELEMENT soilType  (#PCDATA)>
	<!ELEMENT percentRockGravel  (#PCDATA)>
	<!ELEMENT  perSmallRx (#PCDATA)>
	<!ELEMENT perSand  (#PCDATA)>
	<!ELEMENT perLitter (#PCDATA)>
	<!ELEMENT perWood  (#PCDATA)>
	<!ELEMENT perBareSoil  (#PCDATA)>
	<!ELEMENT leafPhenology  (#PCDATA)>
	<!ELEMENT leafType  (#PCDATA)>
	<!ELEMENT physioClass  (#PCDATA)>
	<!-- for the validator: mak be TNC, TURBOVEG-->
	<!ELEMENT importSource  (#PCDATA)>
	
	
	<!-- 
		* observational data that may change over the timescale
		* reflective of the typical time period that various 
		* observations of plots are collected
	-->
	<!ELEMENT plotObservation (parentPlot*, previousObs*, authorObsCode*, 
		plotStartDate*, plotStopDate*, dateAccuracy*, effortLevel*,  strata*, 
		taxonObservations*, communityType*, citation*)>
		
		<!ELEMENT parentPlot (#PCDATA)>
		<!ELEMENT previousObs (#PCDATA)>
		<!ELEMENT authorObsCode (#PCDATA)>
		<!ELEMENT plotStartDate (#PCDATA)>
		<!ELEMENT plotStopDate (#PCDATA)>
		<!ELEMENT dateAccuracy (#PCDATA)>
		<!ELEMENT effortLevel (#PCDATA)>
		
		<!--
			* define the strata here including height and 
			* percent coverage of vegetation
		-->
		<!ELEMENT strata (strataName, strataHeight, strataCover)>
		<!ELEMENT strataName (#PCDATA)>
		<!ELEMENT strataCover (#PCDATA)>
		<!ELEMENT strataHeight (#PCDATA)>

		<!--
			*	Because it was the attempt to keep the database normalized 
			* I have set up this dtd so that the same
		 	* taxon can be represented more than once - 
			*	it should be replicated every time there it occurs in a new stratum
		-->	
		<!ELEMENT taxonObservation (authNameId*, originalAuthority*, 
			strataComposition*, interptretation*)>
			<!ELEMENT authNameId (#PCDATA)>
			<!ELEMENT originalAuthority (#PCDATA)>
			<!ELEMENT strataComposition (strataType, percentCover)>
				<!ELEMENT strataType (#PCDATA)>
				<!ELEMENT percentCover (#PCDATA)>	

			<!ELEMENT interpretation (party, taxonName, authority, usageStartDate, 
				usageStopDate, circum_id, role, date, notes)>
				<!ELEMENT party (#PCDATA)>
				<!ELEMENT taxonName (#PCDATA)>
				<!ELEMENT authority (#PCDATA)>
				<!ELEMENT usageStartDate (#PCDATA)>
				<!ELEMENT usageStopDate (#PCDATA)>
				<!ELEMENT circum_id (#PCDATA)> 
				<!ELEMENT role (#PCDATA)> 
				<!ELEMENT date (#PCDATA)> 
				<!ELEMENT notes (#PCDATA)> 
	
		<!ELEMENT communityAssignment (communityName, CEGLCode, startDate, stopDate)>
			<!ELEMENT communityName (#PCDATA)>
			<!ELEMENT CEGLCode (#PCDATA)>
			<!ELEMENT strartDate (#PCDATA)>
			<!ELEMENT stopDate (#PCDATA)>

		<!ELEMENT citation (title, altTitle, pubDate, edition, editionDate, seriesName, 
		issueIdentification, otherCredentials, 
			page, isbn, issn,citationContributor)>
			<!ELEMENT title (#PCDATA)>
			<!ELEMENT altTitle (#PCDATA)>
			<!ELEMENT pubDate (#PCDATA)>
			<!ELEMENT edition (#PCDATA)>
			<!ELEMENT editionDate (#PCDATA)>
			<!ELEMENT seriesName (#PCDATA)>
			<!ELEMENT issueIdentification (#PCDATA)>
			<!ELEMENT otherCredentials (#PCDATA)>
			<!ELEMENT page (#PCDATA)>
			<!ELEMENT isbn (#PCDATA)>
			<!ELEMENT issn (#PCDATA)>

			<!ELEMENT citationContributor (role,party)>


	<!ELEMENT namedPlace (placeName, placeDescription, gazeteerRef)>
		<!ELEMENT placeName (#PCDATA)>
		<!ELEMENT placeDescription (#PCDATA)>
		<!ELEMENT gazeteerRef (#PCDATA)>

	<!ELEMENT stand (standSize, standDescription, standName)>
		<!ELEMENT standSize (#PCDATA)>
		<!ELEMENT standDescription (#PCDATA)>
		<!ELEMENT standName (#PCDATA)>

	<!ELEMENT  graphic (browseName, browseDescription, browseType, browseData)>
		<!ELEMENT browseName (#PCDATA)>
		<!ELEMENT browseDescription (#PCDATA)>
		<!ELEMENT browseType (#PCDATA)>
		<!ELEMENT browseData (#PCDATA)>

	<!ELEMENT  plotContributor (role,party)> 
	
<!-- Identification of the project contributor-->	
	<!ELEMENT projectContributor (role, party)>
	<!ELEMENT role (#PCDATA)>
	<!ELEMENT party (salutation, givenName, surName, organizationName, 
	positionName, hoursOfService, contactInstructions,  onlineResource, 
	telephone, email, address)>
		<!ELEMENT salutation (#PCDATA)>
		<!ELEMENT givenName (#PCDATA)>
		<!ELEMENT surName (#PCDATA)>
		<!ELEMENT organizationName (#PCDATA)>
		<!ELEMENT positionName (#PCDATA)>
		<!ELEMENT hoursOfService (#PCDATA)>
		<!ELEMENT contactInstructions (#PCDATA)>

			<!ELEMENT telephone (phoneNumber, phoneType)>
			<!ELEMENT phoneNumber (#PCDATA)>
			<!ELEMENT phoneType (#PCDATA)>
			
			<!ELEMENT email (emailAddress)>
			<!ELEMENT emailAddress (#PCDATA)>
			
			<!ELEMENT address (deliveryPoint, city, administrativeArea, 
				postalCode, country, currentFlag)>
			<!ELEMENT deliveryPoint (#PCDATA)>
			<!ELEMENT city (#PCDATA)>
			<!ELEMENT administrativeArea (#PCDATA)>
			<!ELEMENT postalCode (#PCDATA)>
			<!ELEMENT country (#PCDATA)>
			<!ELEMENT currentFlag (#PCDATA)>
			
			
			<!--
				* added this for the veg plot update class
				* so that update xml documents should conform
				* to this
			-->
			<!ELEMENT dbUpdateInstance (constrainingAttribute, constrainingValue, 
			updateTable,	updateAttribute, updateValue)>
			
			<!ELEMENT  constrainingAttribute (#PCDATA)>
			<!ELEMENT  constrainingValue (#PCDATA)>
			<!ELEMENT  updateTable (#PCDATA)>
			<!ELEMENT  updateAttribute (#PCDATA)>
			<!ELEMENT  updateValue (#PCDATA)>

=== NCEAS/vegbank/veg_plot/xml/artificialPlotExample.xml
<?xml version="1.0"?> 
<!DOCTYPE vegPlot SYSTEM "vegPlot2001cv.dtd"> 
<vegPlot> 
 
<project> 
	<projectName>Voyager-tnc</projectName> 
	<projectDescription>to map the Yosemite forest</projectDescription> 
	<projectContributor>null</projectContributor> 

	<plot> 
		<authorPlotCode>YOSE.98K37ARTIFICIAL</authorPlotCode> 
		<plotShape>null</plotShape> 
		<slopeGradient>16 </slopeGradient> 
		<slopeAspect>E </slopeAspect> 
		<surfGeo>-999.25 </surfGeo> 
		<hydrologicRegime>-999.25 </hydrologicRegime> 
		<topoPosition>lowslope</topoPosition> 
		<soilDrainage>rapidly drained </soilDrainage> 
		<elevationValue>7286 </elevationValue> 
		<origLat>null</origLat> 
		<origLong>null</origLong> 
		<plotSize>null</plotSize> 
		<state>California</state> 
		<xCoord>313510.00</xCoord> 
		<yCoord>4200221.00</yCoord> 
		<coordType>zone11</coordType> 

		<plotObservation> 
			<soilDepth>0.00</soilDepth> 
			<soilType>-999.25</soilType> 
			<percentRockGravel>0 </percentRockGravel> 
			<authorObsCode>YOSE.98K377_21_98#0000000</authorObsCode> 
			<perSmallRx>6</perSmallRx> 
			<perSand>3</perSand> 
			<perLitter>1</perLitter> 
			<perWood>5</perWood> 
			<perBareSoil>85</perBareSoil> 
			<leafPhenology>evergreen</leafPhenology> 
			<leafType>Microphyllous</leafType> 
			<physioClass>null</physioClass> 

 
			<strata> 
				<strataName>t1</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>t2</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>t3</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>s1</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>s2</strataName> 
				<strataHeight>0.5 - 1 m</strataHeight> 
				<strataCover>20</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>h</strataName> 
				<strataHeight>0.5 - 1 m</strataHeight> 
				<strataCover>5</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>n</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>v</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<strata> 
				<strataName>e</strataName> 
				<strataHeight>-999.25</strataHeight> 
				<strataCover>0</strataCover> 
			</strata> 
 
			<communityAssignment> 
				<communityName>-999.25</communityName> 
				<CEGLCode>-999.25</CEGLCode> 
			</communityAssignment> 
 
			<taxonObservation> 
				<authNameId>Artemisia tridentata Nutt.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S3</strataType> 
					<percentCover>62.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Chrysothamnus viscidiflorus (Hook.) Nutt.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S3</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Leptodactylon pungens (Torr.) Torr. ex Nutt.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S3</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Purshia tridentata (Pursh) DC.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S2</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Prunus andersonii Gray</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S3</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Hesperostipa comata (Trin.  Rupr.) Barkworth</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Achnatherum hymenoides (Roemer  J.A. Schultes) Barkworth</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Gayophytum diffusum Torr.  Gray</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Elymus elymoides (Raf.) Swezey</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Achnatherum speciosum (Trin.  Rupr.) Barkworth</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Eriastrum wilcoxii (A. Nels.) Mason</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Phacelia bicolor Torr. ex S. Wats.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Eriogonum davidsonii Greene</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Bromus tectorum L.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Mentzelia congesta Nutt. ex Torr.  Gray</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>2.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Leucophysalis nana (Gray) Averett</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Stephanomeria exigua Nutt.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Taraxacum officinale G.H. Weber ex Wiggers</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Ericameria nauseosa ssp. nauseosa var. nauseosa</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>S2</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
 
			<taxonObservation> 
				<authNameId>Phacelia ramosissima Dougl. ex Lehm.</authNameId> 
				<originalAuthority>-999.25</originalAuthority> 
				<strataComposition> 
					<strataType>H</strataType> 
					<percentCover>0.50</percentCover> 
				</strataComposition> 
			</taxonObservation> 
		</plotObservation> 

	</plot> 

	</project> 

 
</vegPlot>
